### ISSUE TITLE
Awsome work, could you add support for panda theme ?

### ISSUE THREAD

**Issue by drmeerkat** [alexanderte/dainty-vs#10]
Panda Theme
panda.siamak.work

**Comment by alexanderte** [comment]
Thanks!

Of course, I’ll add it. I will let you know once it’s done.

**Comment by alexanderte** [comment]
Panda Theme has been added. Run `git pull && yarn && yarn build -p panda-theme` to update and build.

**Comment by alexanderte** [comment]
I’m closing this issue.

**Comment by drmeerkat** [comment]
Thanks a lot!

**Comment by alexanderte** [comment]
You’re welcome. :)
