### ISSUE TITLE
Yarn itself is not listed as a dependency

### ISSUE THREAD

**Issue by detly** [alexanderte/dainty-vs#11]
The installation page (for the Visual Studio builder) lists:

 - Visual Studio 2017
 - Color Theme Editor extension

...as prerequisites. But it also requires Yarn, which itself is non-trivial (because it also needs Node.js, which might also requires Chocolatey, and...). This might affect eg. which machine or VM a person uses to generate themes.

Granted, this becomes clear in the very next section, but it's not obvious if you're just skimming the page for dependencies before going on to the installation step.

**Comment by alexanderte** [comment]
Thanks for the feedback!

I have added Node.js and Yarn to the list.
