### ISSUE TITLE
Cobalt 2 Theme

### ISSUE THREAD

**Issue by warrenbuckley** [alexanderte/dainty-vs#12]
Hello,
Kudos on this project @alexanderte 
I was about to write a .vstheme to fit in the styling with Cobalt 2 from @wesbos and saw it was a 8000 XML file to update eaaak :S

Does this reuse the exact same settings from Wes VSCode theme - https://github.com/wesbos/cobalt2-vscode or has this been a manual port that you have done. I am just curious how close of a match it is please :)

Either way looks like you saved me from a ton of manual work of updaing a 8000 line file, so regardless I am happy, but more intrigued how close the match is :)

Thanks,
Warren

**Comment by alexanderte** [comment]
Hi Warren,

Yes, there are many colors – and for this reason, search–replace is used for a lot of them.

The theme is imported into a Dainty preset, and it is based on the VS Code theme. Dainty presets does support fewer tokens than what can be specified in a VS Code theme. Also, Visual Studio uses fewer tokens than VS Code. However, I have tried to include the most useful tokens into the preset format of Dainty.

Hope this helps. Closing this for now, but feel free to ask if there is anything.
