### ISSUE TITLE
Monokai/Night enum color

### ISSUE THREAD

**Issue by vaindil** [alexanderte/dainty-vs#8]
Thanks for the awesome project! I have a quick request. I don't know what the "correct" way is to do this, but [the color theme I used previously](https://studiostyl.es/schemes/monokai) had a different color for C# enums than for classes/interfaces. It's really helpful to know at a glance whether it's a class property or an enum. Would it be possible to do something similar for Monokai/Monokai Night here?

For example, this is part of your example code with that theme:

![orig](https://user-images.githubusercontent.com/771134/49819796-43afd380-fd44-11e8-93c0-bcd4562bdc0a.png)

And this is with your Monokai Night:

![new](https://user-images.githubusercontent.com/771134/49819844-5b875780-fd44-11e8-800e-ef3f8c82579e.png)

You can see that `IActionResult` and `ResponseCacheLocation` are the same color, even though the former is an interface and the latter is an enum.

Totally fine if you don't want to, like I said I don't know what's "correct" for the theme. Thanks again, this project is fantastic!

**Comment by alexanderte** [comment]
I’m glad you enjoy using Dainty!

I understand your concern. Dainty for the most part uses the same kind of highlighting rules as the default themes. In both the default Dark and Light, enums and interfaces are colored the same. I don’t really want to diverge from that until I have enough data (e.g. an issue on GitHub with many upvotes) clearly suggesting that things should be done differently.

At this moment I’d suggest you to use a feature that currently isn’t documented. Try this in your `configuration.jsonc`:

    {
      "preset": "monokai",
      "customizations": {
        "__categories": {
          "ColorizedSignatureHelp colors": {
            "enum name": [[null, "#f5901f"], [null, "#f5901f"]]
          }
        }
      }
    }

**Comment by vaindil** [comment]
No problem, that's completely understandable. That configuration option works perfectly as a replacement, thank you so much!

**Comment by alexanderte** [comment]
I’m glad it works. You’re welcome!

**Comment by alexanderte** [comment]
@vaindil If you upgrade to the latest version (`git pull && yarn && yarn build`) then you need to update your `configuration.jsonc`. Here is what it should look like now:

    {
      "preset": "monokai",
      "colors": {
        "tokenEnum": {
          "hex": "#f5901f"
        }
      },
      "customizations": {
        "__categories": {
          "ColorizedSignatureHelp colors": {
            "enum name": [null, "tokenEnum-exact"]
          }
        }
      }
    }

**Comment by vaindil** [comment]
Perfect, updated to this and everything is still good. Thanks again!
